### ISSUE TITLE
README instructions failed

### ISSUE THREAD

**Issue by darcy-clark** [Microsoft/PowerBI-visuals-TimeBrush#26]
I went through the README following the directions on how to set up the repo for development, however when I ran `npm run build` I would keep getting the error that a build script was not found. Is the README outdated?

**Comment by stopyoukid** [comment]
Yes, I was actually working on that when this issue was posted: https://github.com/Microsoft/PowerBI-visuals-TimeBrush/pull/27

Until that gets merged, you'll need to install [yarn](https://yarnpkg.com) and lerna (`npm install -g lerna@2.0.0-beta.34`)

When you have those installed, you just need to run 
`lerna --scope @essex/timebrush run test && lerna run test --ignore @essex/timebrush`.

This will produce a `pbiviz` in the `packages/timebrush-powerbi/dist` directory.

With the pull request, I'm also going to be adding some convenience scripts, so in the future, all you'll need to do is run, `yarn test` from the root.

**Comment by kodonnell** [comment]
I'm having trouble with the current develop branch (phantomjs isn't playing nicely with karma) - is there a way (even hacky) for me to build the pbiviz file without testing first?

**Comment by stopyoukid** [comment]
@kodonnell I've made an update to fix the tests, let me know if that fixes it.

**Comment by kodonnell** [comment]
Nice - fixed.
